name: Sync output.txt to Gitverse

on:
  push:
    paths:
      - 'output.txt'
  workflow_dispatch:   # позволяет запуск вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Clone Gitverse repo
        env:
          TOKEN: ${{ secrets.GITVERSE_TOKEN }}
        run: |
          git clone https://$TOKEN@gitverse.ru/Xalador/AutoConfig.git gitverse

      - name: Compare files
        id: check
        run: |
          if [ -f gitverse/output.txt ]; then
            if cmp -s output.txt gitverse/output.txt; then
              echo "same=true" >> $GITHUB_OUTPUT
            else
              echo "same=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "same=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy file
        if: steps.check.outputs.same == 'false'
        run: |
          cp output.txt gitverse/

      - name: Commit and push
        if: steps.check.outputs.same == 'false'
        run: |
          cd gitverse
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output.txt
          git commit -m "Auto sync from GitHub"
          git push
