name: Build VPN Subscription

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1️⃣ Забираем репозиторий
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ создаем папку
      - name: Create build folder
        run: mkdir -p build

      # 3️⃣ очищаем файл
      - name: Clear output
        run: echo "" > build/output.txt

      # 4️⃣ читаем источники
      - name: Build subscription
        run: |
          while IFS= read -r url || [ -n "$url" ]; do
            if [ -n "$url" ]; then
              echo "Fetching $url"
              curl -L "$url" >> build/output.txt
              echo "" >> build/output.txt
            fi
          done < NECHAEV_VPN.txt

      # 5️⃣ коммитим изменения
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add build/output.txt

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update subscription"
            git push
          fi

      # 6️⃣ зеркалим в Gitverse
      - name: Mirror to Gitverse
        run: |
          git remote add gitverse https://${{ secrets.GITVERSE_TOKEN }}@gitverse.ru/Xalador/AutoConfig.git
          git push gitverse HEAD:main --force
