name: Upload VPN to VK

on:
  workflow_dispatch:
  push:
    paths:
      - output.txt

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Upload to VK
        run: |
          RESPONSE=$(curl -s "https://api.vk.com/method/docs.getMessagesUploadServer?type=doc&group_id=${{ secrets.VK_GROUP_ID }}&access_token=${{ secrets.VK_TOKEN }}&v=5.131")

          UPLOAD_URL=$(echo $RESPONSE | jq -r '.response.upload_url')

          UPLOAD=$(curl -s -F "file=@output.txt" "$UPLOAD_URL")

          FILE=$(echo $UPLOAD | jq -r '.file')

          curl -s "https://api.vk.com/method/docs.save?file=$FILE&title=output.txt&access_token=${{ secrets.VK_TOKEN }}&v=5.131"

          echo "Done"
