name: Upload VPN to VK

on:
  workflow_dispatch:
  push:
    paths:
      - output.txt

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check secrets
        run: |
          if [ -z "${{ secrets.VK_TOKEN }}" ]; then
            echo "❌ VK_TOKEN is empty!"
            exit 1
          fi

          if [ -z "${{ secrets.VK_GROUP_ID }}" ]; then
            echo "❌ VK_GROUP_ID is empty!"
            exit 1
          fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Upload file to VK
        run: |

          echo "🚀 Getting upload server..."

          RESPONSE=$(curl -s "https://api.vk.com/method/docs.getMessagesUploadServer?type=doc&group_id=${{ secrets.VK_GROUP_ID }}&access_token=${{ secrets.VK_TOKEN }}&v=5.131")

          echo "Server response:"
          echo $RESPONSE

          UPLOAD_URL=$(echo $RESPONSE | jq -r '.response.upload_url')

          if [ "$UPLOAD_URL" = "null" ] || [ -z "$UPLOAD_URL" ]; then
            echo "❌ Failed to get upload URL"
            exit 1
          fi

          echo "📤 Uploading file..."

          UPLOAD=$(curl -s -F "file=@output.txt" "$UPLOAD_URL")

          echo "Upload response:"
          echo $UPLOAD

          FILE=$(echo $UPLOAD | jq -r '.file')

          if [ "$FILE" = "null" ] || [ -z "$FILE" ]; then
            echo "❌ Upload failed"
            exit 1
          fi

          echo "💾 Saving file in VK..."

          curl -s "https://api.vk.com/method/docs.save?file=$FILE&title=output.txt&access_token=${{ secrets.VK_TOKEN }}&v=5.131"

          echo "✅ DONE"
